### ISSUE TITLE
tensorflow2.0

### ISSUE THREAD

**Issue by BenoitLebreton** [MAIF/melusine#5]
Hello,

Since the setup contains the requirement 'tensorflow>=1.10.0'
The installation I launched installed tensorflow=2.0.0a0

It causes the issue : module 'tensorflow' has no attribute 'get_default_graph'
So we need to downgrade the version of tensorflow (1.13.1 for example) or to upgrade the code in order to make it work with tensorflow 2.0
Best regards,

**Comment by BenoitLebreton** [comment]
#6 
Requirements : tensorflow <=1.13.1
